function expA_raw = exp_SE2(in1)
%exp_SE2
%    expA_raw = exp_SE2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Mar-2025 16:43:07

A1 = in1(1,:);
A2 = in1(2,:);
A3 = in1(3,:);
t2 = cos(A1);
t3 = sin(A1);
t4 = 1.0./A1;
t5 = A1.*1i;
t6 = exp(t5);
t7 = -t5;
t8 = exp(t7);
t9 = t6-1.0;
t10 = t9.^2;
expA_raw = reshape([t2,t3,0.0,-t3,t2,0.0,A2.*t3.*t4+(A3.*t4.*t8.*t10)./2.0,A3.*t3.*t4-(A2.*t4.*t8.*t10)./2.0,1.0],[3,3]);
end
