function dexpA_raw = K_SE2(in1)
%K_SE2
%    dexpA_raw = K_SE2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Mar-2025 16:43:08

A1 = in1(1,:);
A2 = in1(2,:);
A3 = in1(3,:);
t2 = sin(A1);
t3 = 1.0./A1;
t5 = A1.*1i;
t6 = A1.*2.0i;
t4 = t3.^2;
t7 = exp(t5);
t8 = exp(t6);
t9 = -t5;
t11 = t2.*t3;
t10 = exp(t9);
t12 = t7-1.0;
t13 = A1.*t7.*2.0;
t14 = t8.*1i;
t15 = t12.^2;
t16 = t13+t14-1i;
t17 = (t3.*t10.*t15)./2.0;
dexpA_raw = reshape([1.0,(A2.*t4.*t10.*t16)./2.0+(A3.*t4.*t10.*t15)./2.0,A2.*t4.*t10.*t15.*(-1.0./2.0)+(A3.*t4.*t10.*t16)./2.0,0.0,t11,t17,0.0,-t17,t11],[3,3]);
end
