function dexpA_inv_raw = Kinv_SE2(in1)
%Kinv_SE2
%    dexpA_inv_raw = Kinv_SE2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Mar-2025 16:43:08

A1 = in1(1,:);
A2 = in1(2,:);
A3 = in1(3,:);
t2 = 1.0./A1;
t3 = A1./2.0;
t4 = A1.*1i;
t5 = exp(t4);
t6 = A1.*t5;
t7 = t5-1.0;
t8 = t5.*1i;
t9 = t5.*2.0i;
t10 = 1.0./t7;
t11 = t8+1i;
t12 = A1+t6+t9-2.0i;
t13 = t3.*t10.*t11;
dexpA_inv_raw = reshape([1.0,A3./2.0-A2.*t2.*t10.*t12.*5.0e-1i,A2.*(-1.0./2.0)-A3.*t2.*t10.*t12.*5.0e-1i,0.0,t13,t3,0.0,-t3,t13],[3,3]);
end
