function skew_fun = skew_SE2(in1)
%skew_SE2
%    SKEW_FUN = skew_SE2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Mar-2025 16:42:39

A1 = in1(1,:);
A2 = in1(2,:);
A3 = in1(3,:);
skew_fun = reshape([0.0,A1,0.0,-A1,0.0,0.0,A2,A3,0.0],[3,3]);
end
