function skew_dual_fun = skewd_SE2(in1)
%skewd_SE2
%    SKEW_DUAL_FUN = skewd_SE2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Mar-2025 16:42:39

A1 = in1(1,:);
A2 = in1(2,:);
A3 = in1(3,:);
t2 = A1./2.0;
skew_dual_fun = reshape([0.0,t2,0.0,-t2,0.0,0.0,A2,A3,0.0],[3,3]);
end
