function unskew_dual_fun = unskewd_SE2(in1)
%unskewd_SE2
%    UNSKEW_DUAL_FUN = unskewd_SE2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Mar-2025 16:42:39

As1_2 = in1(4);
As1_3 = in1(7);
As2_1 = in1(2);
As2_3 = in1(8);
unskew_dual_fun = [-As1_2+As2_1;As1_3;As2_3];
end
