function ad_fun = ad_SE3(in1)
%ad_SE3
%    AD_FUN = ad_SE3(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Mar-2025 17:07:23

A1 = in1(1,:);
A2 = in1(2,:);
A3 = in1(3,:);
A4 = in1(4,:);
A5 = in1(5,:);
A6 = in1(6,:);
t2 = -A1;
t3 = -A2;
t4 = -A3;
ad_fun = reshape([0.0,A3,t3,0.0,A6,-A5,t4,0.0,A1,-A6,0.0,A4,A2,t2,0.0,A5,-A4,0.0,0.0,0.0,0.0,0.0,A3,t3,0.0,0.0,0.0,t4,0.0,A1,0.0,0.0,0.0,A2,t2,0.0],[6,6]);
end
