function skew_dual_fun = skewd_SE3(in1)
%skewd_SE3
%    SKEW_DUAL_FUN = skewd_SE3(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Mar-2025 17:07:24

A1 = in1(1,:);
A2 = in1(2,:);
A3 = in1(3,:);
A4 = in1(4,:);
A5 = in1(5,:);
A6 = in1(6,:);
t2 = A1./2.0;
t3 = A2./2.0;
t4 = A3./2.0;
skew_dual_fun = reshape([0.0,t4,-t3,0.0,-t4,0.0,t2,0.0,t3,-t2,0.0,0.0,A4,A5,A6,0.0],[4,4]);
end
