function skew_fun = skew_SE3(in1)
%skew_SE3
%    SKEW_FUN = skew_SE3(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Mar-2025 17:07:23

A1 = in1(1,:);
A2 = in1(2,:);
A3 = in1(3,:);
A4 = in1(4,:);
A5 = in1(5,:);
A6 = in1(6,:);
skew_fun = reshape([0.0,A3,-A2,0.0,-A3,0.0,A1,0.0,A2,-A1,0.0,0.0,A4,A5,A6,0.0],[4,4]);
end
