function unskew_dual_fun = unskewd_SE3(in1)
%unskewd_SE3
%    UNSKEW_DUAL_FUN = unskewd_SE3(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Mar-2025 17:07:24

As1_2 = in1(5);
As1_3 = in1(9);
As1_4 = in1(13);
As2_1 = in1(2);
As2_3 = in1(10);
As2_4 = in1(14);
As3_1 = in1(3);
As3_2 = in1(7);
As3_4 = in1(15);
unskew_dual_fun = [-As2_3+As3_2;As1_3-As3_1;-As1_2+As2_1;As1_4;As2_4;As3_4];
end
