function unskew_fun = unskew_SE3(in1)
%unskew_SE3
%    UNSKEW_FUN = unskew_SE3(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Mar-2025 17:07:24

As1_2 = in1(5);
As1_3 = in1(9);
As1_4 = in1(13);
As2_1 = in1(2);
As2_3 = in1(10);
As2_4 = in1(14);
As3_1 = in1(3);
As3_2 = in1(7);
As3_4 = in1(15);
unskew_fun = [As2_3.*(-1.0./2.0)+As3_2./2.0;As1_3./2.0-As3_1./2.0;As1_2.*(-1.0./2.0)+As2_1./2.0;As1_4;As2_4;As3_4];
end
